name: CI/CD Workflow

on: push

jobs:
  Test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    
    - name: Chekout repo
      uses: rohmanngmbh/action-checkout-repo@v1.3.4
      
    - name: Run Python Script
      run: python hello.py
  Build:
      name: Build
      runs-on: ubuntu-latest
      needs: Test
      steps:
      
      - name: Checkout repo
        uses: rohmanngmbh/action-checkout-repo@v1.3.4

      - name: Build artifact for ubuntu-latest
        run: go build artifact.go
      
      - name: Upload artifact for linux
        uses: actions/upload-artifact@v1.0.0
        with:
          name: artifact
          path: .
